// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhxomwvmpoeblpddhpno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeG9td3ZtcG9lYmxwZGRocG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTIwNDUsImV4cCI6MjA1NjI4ODA0NX0.Kr6vqkBhd7MyOTcgG6TbsosrpxwYbPEqH1rubRdYx-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);